### PR TITLE
feat : getLCs test created : closes #9

### LINKED ISSUE #9: feat : write tests for LongestCommonSubsequence::getLCS
### What would you like to Propose?

Improve the coverage of the LongestCommonSubsequence::getLCS method by implementing four new tests.

### Issue details

adding tests

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tjex**
Do I understand correctly that only the expected scenario needs to be tested?
Or does there also need to be test implementation for 'incorrect' conditions. 

eg. This function takes two strings and finds he longest common subsequence. 
It has an if statement to test if one of the strings is empty, and will then return null. 

Should I write a test that checks the if statement, by passing in one string + one empty string?..

### CODE REVIEW

**Comment by adamezzaim** [comment]
Hello, if I understood correctly what you are saying, then yes, you should test with empty strings to check whether the function correctly returns null.

**Review by einbergisak — CHANGES_REQUESTED** [review]
The test looks good, but it's missing documentation (comments) and assertions in regards to the requirements for entering the branches that the tests cover.  See instruction "2." in Task 2 in the assignment. 

And there is still branch coverage on the other functions in the class, but it is only required for the getLCS function and not the other functions of the class, as mentioned in a previous review.

Also, should this PR close issue #9 as mentioned in the PR title? The PR only includes one of four required tests (per person). We're not required to implement all of our individual tests for one specific function, but I just wanted to clarify if you intend to implement the remaining three tests for this function (which makes this PR either incomplete or misnamed) or for other functions of high complexity?

And last thing: this PR includes a lot of "wip" commits, which shouldn't be part of the merge. So make sure to squash them before merging! :)

**Comment by tjex** [comment]
thanks for the detailed feedback. 

> but it's missing documentation (comments) and assertions in regards to the requirements for entering the branches that the tests cover.

by comments you just mean like this (from your test file isac)?:
```java
    /**
     * Test if the method works with input arrays consisting only of one row.
     */
    @Test
    public void BinarySearch2dArrayTestOneRow() {
    // ... //
   }

```

I'm not clear on what is meant by 'assertions in regards to the requirements for entering branches that the tests cover'. I'll research into it and ask questions if needed. Sorry, this is where my inexperience starts to weigh the group down a bit. But would prefer to be transparent about it rather than lurking in the shadows. 

I will also implement some more tests for this method (inputting empty strings) etc. And see how many I can get done just in this method (hopefully 4). 

noted regarding the wip comments 👍 thanks

**Comment by tjex** [comment]
done. But I'm not sure if I've constructed the assert comments correctly.
Should it be written more in terms of 'asserting' that the input arguments are as expected?
As it is, I've written the comments to assert that the correct value is returned based on differing states of input arguments.

**Review by adamezzaim — APPROVED** [review]

**Review by einbergisak — APPROVED** [review]

**Pull request merged**
